Title:	cant resolve xrefs when target exists in different corpus
Stat:	closed
Disp:	done
Prio:	high
Cats:	bug
Reqtrs:	Jim Breen
AssdTo:	

2008-11-20 10:10:50 sysad
  Ref: email from Jim Breen, 2008-11-16
  Xref resolution failed due to multiple targets even though
  there was only one potential target in the jmdict corpus.
  Problem was that matching entry also existed in jmnedict.

2008-11-20 10:10:50 sysad
  Did a workaround by changing jdb.xresolv_xref() call in
  web/cgi/edconf.py to restrict target search to the current
  corpus.  This is a temp workaround because long term, we
  want to be able to allow inter-corpus xrefs. 

  Fixed in changeset f9a98c38e95a 2008-11-22.
