Title:	cant resolve xrefs when unapproved entries exist
Stat:	closed
Disp:	done
Prio:	high
Cats:	dev
Reqtrs:	Jim Breen
AssdTo:	

2008-11-20 10:10:50 sysad
  Ref: email from Jim Breen, 2008-11-17.
  In jmdictdb, programs that need to resolve a kanji/reading
  string to a database entry in order to create an xref usually
  call python/lib/jdb.py.resolv_xref() with the "one_entry_only"
  argument which will result in an error if more than one entry
  is found that matches the k/r text.

  A problem is that an entry (defined by seq number) may have
  multiple database entries that have various statuses (active,
  unapproved, rejected, etc) and in general we want xrefs created
  for the active approved entry (should be only one) and all
  active unapproved entries (may be many).  Currently when one
  tries to add an xref using the edform/edconf cgi pages to an
  entry with unapproved edits, edconf produces an error because 
  it sees multiple entries.

2008-11-20 10:10:50 sysad
  Changed the meaning of jdb.py.resolv_xref()'s "one_entr_only"
  parameter to actually mean, "one seq number only".  So it will
  now generate xrefs to all active and new (but not rejected
  or deleted" entries with the same seq number and will only
  raise a "multiple targets" error if more than one seq number
  occurs in the potential target entries set.

  Fixed in changeset f9a98c38e95a 2008-11-22.
  