Title:	Edconf page failing on Arakawa 
Stat:	open
Disp:	
Prio:	high
Cats:	dev
Reqtrs:	
AssdTo:	stuart

2010-04-12 10:30:00 stuart
  When I tried to entry as new entry on Arakawa's jmdictdb 
  site, using the url, 

  http://www.edrdg.org/~smg/cgi-bin/edconf.py?src=1&kanj=%E5%BD%A2%E6%85%8B%E9%A3%9F&rdng=%E3%81%91%E3%81%84%E3%81%9F%E3%81%84%E3%81%97%E3%82%87%E3%81%8F&sens=[1][n]%0D%0A+meal+of+used+cell+phones&comment=&reference=&name=me&email=&svc=jmdict&seq=&srcnote=&notes=

  the edconf.py page dies with the traceback

  Traceback (most recent call last):
  File "/home/smg/public_html/cgi-bin/edconf.py", line 282, in <module>
    main (args, opts)
  File "/home/smg/public_html/cgi-bin/edconf.py", line 93, in main
    entr, perrs = parse (intxt)
  File "/home/smg/public_html/cgi-bin/edconf.py", line 270, in parse
    parser = jelparse.create_parser (lexer, tokens)
  File "../lib/jelparse.py", line 941, in create_parser
    JelParser = ply.yacc.yacc (**args)
  File "/usr/local/lib/python2.6/site-packages/ply/yacc.py", line 3091, in yacc
    debuglog = PlyLogger(open(debugfile,"w"))
  IOError: [Errno 13] Permission denied: 'parser.out'

2010-04-12 11:32:00 stuart
  Problem was that there was a parser.out file in 
  ~/public_html/cgi-bin/ owned by user stuart.  I deleted it,
  temporarily changed the directory permissions to 777, reran
  (sucessfully this time) the web page, changer perms back to
  755.

  The newly created parser.out file is ownded by "www-data"
  so probably could have changed owner of old parser.out
  file to this to fix.

  Hopefully this file is not written every time. 
